services:

  traefik:
    container_name: traefik
    hostname: traefik.mac.example.com
    image: traefik:3.1.6
    restart: unless-stopped
    command:
      - "--api=true"
      - "--ping=true"
      - "--ping.terminatingStatusCode=204"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.file.watch=true"
      - "--entrypoints.http.address=:80"
      - "--entrypoints.https.address=:443"
      - "--accesslog=true"
      - "--accesslog.filepath=/access.log"
      - "--entrypoints.websecure.http.tls.domains[0].main=mac.example.com"
      - "--entrypoints.websecure.http.tls.domains[0].sans=traefik.mac.example.com,*.mac.example.dev"
    healthcheck:
      test: traefik healthcheck --ping
      interval: 3s
      timeout: 1s
      start_period: 3s
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./certs:/certs
      - "./traefik/access.log:/access.log"
      - ./traefik/tls.toml:/etc/traefik/dynamic/tls.toml
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`traefik.mac.example.com`) || Host(`mac.example.com`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.entrypoints=https"

  vault:
    container_name: vault
    hostname: vault.mac.example.com
    image: hashicorp/vault-enterprise:1.19.0-ent
    restart: unless-stopped
    ports:
      - 8200:8200
      - 8201:8201
    volumes:
      - ./vault/data:/vault/data
      - ./vault/conf:/vault/conf
      - ./vault/audit:/vault/audit
      - ./vault/snapshots:/vault/snapshots
      - ./vault/plugins:/vault/plugins
      - ./certs:/certs
      - ./vault.hclic:/vault.hclic
    environment:
      - VAULT_ADDR=https://vault.mac.example.com:8200
      - VAULT_API_ADDR=https://vault.mac.example.com:8200
      - VAULT_CLUSTER_ADDR=https://vault.mac.example.com:8201
      - VAULT_SKIP_VERIFY=true
      - VAULT_UI=true
      - VAULT_LICENSE_PATH=/vault.hclic
    command: vault server -config=/vault/conf/vault.hcl
    healthcheck:
      test: wget --no-verbose --tries=1 --spider $VAULT_ADDR/v1/sys/health?sealedcode=200&uninitcode=200 || exit 1
      interval: 3s
      timeout: 1s
      start_period: 5s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vault.rule=Host(`vault.mac.example.com`)"
      - "traefik.http.routers.vault.tls.domains[0].sans=vault.mac.example.com"
      - "traefik.http.routers.vault.entrypoints=https"
      - "traefik.http.routers.vault.tls=true"
