#!/bin/bash

export VAULT_TOKEN=$(cat ~/data/vault-init.json | jq -r .root_token)
export VAULT_SEAL_KEY=$(cat ~/data/vault-init.json | jq -r .unseal_keys_b64[])
export VAULT_ADDR=https://vault.mac.example.com:8200
export VAULT_SKIP_VERIFY=true

